export const PHOTO_UPLOAD = {
  ALLOWED_TYPES: [
    "image/jpeg",
    "image/jpg",
    "image/png",
    "image/webp",
    "image/gif",
    "image/svg+xml",
    "application/pdf",
    "text/plain",
    "text/csv",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "video/mp4",
    "video/webm",
    "video/quicktime",
  ],
  MAX_SIZE: 10 * 1024 * 1024,
  MAX_FILES: 10,
  FOLDER: "shipments/photos",
};
